version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: evotech_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=HelloFace34
      - POSTGRES_DB=EvotechSolution
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  server:
    build: ./backend
    container_name: evotech_server
    ports:
      - "3000:5000"
    environment:
      - PORT=5000
      - DB_USER=postgres
      - DB_PASSWORD=HelloFace34
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=EvotechSolution
      - JWT_SECRET=evotech_secret_key_2026
      - CORS_ORIGIN=*
    depends_on:
      - postgres
    restart: always

  client:
    build: ./frontend
    container_name: evotech_client
    ports:
      - "8080:80"
    depends_on:
      - server
    restart: always

volumes:
  pgdata:
